trainingInput:
  scaleTier: CUSTOM
  masterType: standard_gpu
  runtimeVersion: "1.12"
  pythonVersion: "3.5"
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: f_measure
    maxTrials: 20
    maxParallelTrials: 2
    params:
      - parameterName: num-epochs
        type: INTEGER
        minValue: 5
        maxValue: 40
      - parameterName: num-layers
        type: INTEGER
        minValue: 1
        maxValue: 5
      - parameterName: learning-rate
        type: DOUBLE
        minValue: 0.000001
        maxValue: 0.0001
      - parameterName: dropout-rate
        type: DOUBLE
        minValue: 0.0
        maxValue: 0.5
      - parameterName: filter-prob
        type: DOUBLE
        minValue: 0.5
        maxValue: 1.0
      - parameterName: lstm-size
        type: INTEGER
        minValue: 128
        maxValue: 512
      - parameterName: seq-len
        type: DISCRETE
        discreteValues:
          - 5
          - 10
          - 15
          - 20
          - 30
          - 40
          - 50
      - parameterName: train-batch-size
        type: DISCRETE
        discreteValues:
          - 16
          - 32
          - 64
          - 128
          - 256
