runtime: python37

handlers:
- url: /upload
  script: auto

env_variables:
  MODEL_NAME: 'EnergyDisaggregationModel'
  SEQ_LEN: 20
  DATASET_ID: 'EnergyDisaggregation'
  PUB_TOPIC: 'pred'
  GOOGLE_APPLICATION_CREDENTIALS: 'e2e_demo_credential.json'
  GOOGLE_CLOUD_PROJECT: 'my-project-fy'
